# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/pi/Documents/PycharmProjects/FamilyOrganizer/organizer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import os

if os.environ.get("DISPLAY", "") == "":
    print("no display found. Using :0.0")
    os.environ.__setitem__("DISPLAY", ":0.0")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(512, 300))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 600))
        MainWindow.setTabletTracking(True)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        MainWindow.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pageWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.pageWidget.setAutoFillBackground(False)
        self.pageWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pageWidget.setObjectName("pageWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.gridLayout = QtWidgets.QGridLayout(self.mainPage)
        self.gridLayout.setObjectName("gridLayout")
        self.mainOverview = QtWidgets.QToolBox(self.mainPage)
        self.mainOverview.setFrameShape(QtWidgets.QFrame.Panel)
        self.mainOverview.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mainOverview.setLineWidth(1)
        self.mainOverview.setMidLineWidth(4)
        self.mainOverview.setObjectName("mainOverview")
        self.meetingsOverview = QtWidgets.QWidget()
        self.meetingsOverview.setGeometry(QtCore.QRect(0, 0, 734, 373))
        self.meetingsOverview.setObjectName("meetingsOverview")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.meetingsOverview)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.meetings_checkboxLayout = QtWidgets.QGridLayout()
        self.meetings_checkboxLayout.setObjectName("meetings_checkboxLayout")
        self.meetings_checkboxFabienne = QtWidgets.QCheckBox(self.meetingsOverview)
        self.meetings_checkboxFabienne.setObjectName("meetings_checkboxFabienne")
        self.meetings_checkboxLayout.addWidget(
            self.meetings_checkboxFabienne, 2, 0, 1, 1
        )
        self.meetings_checkboxKatja = QtWidgets.QCheckBox(self.meetingsOverview)
        self.meetings_checkboxKatja.setObjectName("meetings_checkboxKatja")
        self.meetings_checkboxLayout.addWidget(self.meetings_checkboxKatja, 0, 0, 1, 1)
        self.meetings_checkboxFabian = QtWidgets.QCheckBox(self.meetingsOverview)
        self.meetings_checkboxFabian.setObjectName("meetings_checkboxFabian")
        self.meetings_checkboxLayout.addWidget(self.meetings_checkboxFabian, 1, 0, 1, 1)
        self.meetings_checkboxMio = QtWidgets.QCheckBox(self.meetingsOverview)
        self.meetings_checkboxMio.setObjectName("meetings_checkboxMio")
        self.meetings_checkboxLayout.addWidget(self.meetings_checkboxMio, 3, 0, 1, 1)
        self.meetings_checkboxJona = QtWidgets.QCheckBox(self.meetingsOverview)
        self.meetings_checkboxJona.setObjectName("meetings_checkboxJona")
        self.meetings_checkboxLayout.addWidget(self.meetings_checkboxJona, 5, 0, 1, 1)
        self.meetings_checkboxMika = QtWidgets.QCheckBox(self.meetingsOverview)
        self.meetings_checkboxMika.setObjectName("meetings_checkboxMika")
        self.meetings_checkboxLayout.addWidget(self.meetings_checkboxMika, 4, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.meetings_checkboxLayout)
        self.meetingsList = QtWidgets.QListWidget(self.meetingsOverview)
        self.meetingsList.setObjectName("meetingsList")
        self.horizontalLayout_6.addWidget(self.meetingsList)
        self.mainOverview.addItem(self.meetingsOverview, "")
        self.childrenOverview = QtWidgets.QWidget()
        self.childrenOverview.setGeometry(QtCore.QRect(0, 0, 103, 103))
        self.childrenOverview.setObjectName("childrenOverview")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.childrenOverview)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.childrenOverviewTable = QtWidgets.QTableWidget(self.childrenOverview)
        self.childrenOverviewTable.setObjectName("childrenOverviewTable")
        self.childrenOverviewTable.setColumnCount(4)
        self.childrenOverviewTable.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.childrenOverviewTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.childrenOverviewTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.childrenOverviewTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.childrenOverviewTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.childrenOverviewTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.childrenOverviewTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.childrenOverviewTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.childrenOverviewTable.setHorizontalHeaderItem(3, item)
        self.gridLayout_10.addWidget(self.childrenOverviewTable, 0, 0, 1, 1)
        self.mainOverview.addItem(self.childrenOverview, "")
        self.woodOverview = QtWidgets.QWidget()
        self.woodOverview.setGeometry(QtCore.QRect(0, 0, 734, 386))
        self.woodOverview.setObjectName("woodOverview")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.woodOverview)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.wood_inputLayout = QtWidgets.QVBoxLayout()
        self.wood_inputLayout.setObjectName("wood_inputLayout")
        self.wood_inputDisplay = QtWidgets.QLCDNumber(self.woodOverview)
        self.wood_inputDisplay.setDigitCount(3)
        self.wood_inputDisplay.setMode(QtWidgets.QLCDNumber.Dec)
        self.wood_inputDisplay.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.wood_inputDisplay.setObjectName("wood_inputDisplay")
        self.wood_inputLayout.addWidget(self.wood_inputDisplay)
        self.wood_inputRadioButtonPiece = QtWidgets.QRadioButton(self.woodOverview)
        self.wood_inputRadioButtonPiece.setChecked(True)
        self.wood_inputRadioButtonPiece.setObjectName("wood_inputRadioButtonPiece")
        self.wood_inputLayout.addWidget(self.wood_inputRadioButtonPiece)
        self.wood_nputRadioButtonStack = QtWidgets.QRadioButton(self.woodOverview)
        self.wood_nputRadioButtonStack.setObjectName("wood_nputRadioButtonStack")
        self.wood_inputLayout.addWidget(self.wood_nputRadioButtonStack)
        self.wood_inputDial = QtWidgets.QDial(self.woodOverview)
        self.wood_inputDial.setMinimumSize(QtCore.QSize(160, 160))
        self.wood_inputDial.setMinimum(-15)
        self.wood_inputDial.setMaximum(15)
        self.wood_inputDial.setProperty("value", 0)
        self.wood_inputDial.setSliderPosition(0)
        self.wood_inputDial.setOrientation(QtCore.Qt.Horizontal)
        self.wood_inputDial.setInvertedAppearance(False)
        self.wood_inputDial.setInvertedControls(False)
        self.wood_inputDial.setObjectName("wood_inputDial")
        self.wood_inputLayout.addWidget(self.wood_inputDial)
        self.wood_inputPushButtonAgree = QtWidgets.QPushButton(self.woodOverview)
        self.wood_inputPushButtonAgree.setObjectName("wood_inputPushButtonAgree")
        self.wood_inputLayout.addWidget(self.wood_inputPushButtonAgree)
        self.gridLayout_4.addLayout(self.wood_inputLayout, 0, 0, 1, 1)
        self.wood_graphicsView = QtWidgets.QGraphicsView(self.woodOverview)
        self.wood_graphicsView.setObjectName("wood_graphicsView")
        self.gridLayout_4.addWidget(self.wood_graphicsView, 0, 1, 1, 1)
        self.wood_progressBar = QtWidgets.QProgressBar(self.woodOverview)
        self.wood_progressBar.setProperty("value", 24)
        self.wood_progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.wood_progressBar.setObjectName("wood_progressBar")
        self.gridLayout_4.addWidget(self.wood_progressBar, 1, 0, 1, 2)
        self.mainOverview.addItem(self.woodOverview, "")
        self.gridLayout.addWidget(self.mainOverview, 1, 2, 1, 1)
        self.mainbuttonsLayout = QtWidgets.QGridLayout()
        self.mainbuttonsLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mainbuttonsLayout.setContentsMargins(0, -1, 0, -1)
        self.mainbuttonsLayout.setObjectName("mainbuttonsLayout")
        self.mainbutton_recipes = QtWidgets.QPushButton(self.mainPage)
        self.mainbutton_recipes.setMinimumSize(QtCore.QSize(96, 96))
        self.mainbutton_recipes.setMaximumSize(QtCore.QSize(96, 96))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mainbutton_recipes.setFont(font)
        self.mainbutton_recipes.setObjectName("mainbutton_recipes")
        self.mainbuttonsLayout.addWidget(self.mainbutton_recipes, 2, 1, 1, 1)
        self.mainbutton_shopping_list = QtWidgets.QPushButton(self.mainPage)
        self.mainbutton_shopping_list.setMinimumSize(QtCore.QSize(96, 96))
        self.mainbutton_shopping_list.setMaximumSize(QtCore.QSize(96, 96))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mainbutton_shopping_list.setFont(font)
        self.mainbutton_shopping_list.setObjectName("mainbutton_shopping_list")
        self.mainbuttonsLayout.addWidget(self.mainbutton_shopping_list, 2, 0, 1, 1)
        self.mainbutton_children = QtWidgets.QPushButton(self.mainPage)
        self.mainbutton_children.setMinimumSize(QtCore.QSize(96, 96))
        self.mainbutton_children.setMaximumSize(QtCore.QSize(96, 96))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mainbutton_children.setFont(font)
        self.mainbutton_children.setCheckable(False)
        self.mainbutton_children.setAutoExclusive(False)
        self.mainbutton_children.setObjectName("mainbutton_children")
        self.mainbuttonsLayout.addWidget(self.mainbutton_children, 0, 0, 1, 1)
        self.mainbutton_calendar = QtWidgets.QPushButton(self.mainPage)
        self.mainbutton_calendar.setMinimumSize(QtCore.QSize(96, 96))
        self.mainbutton_calendar.setMaximumSize(QtCore.QSize(96, 96))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.mainbutton_calendar.setFont(font)
        self.mainbutton_calendar.setCheckable(False)
        self.mainbutton_calendar.setChecked(False)
        self.mainbutton_calendar.setAutoExclusive(False)
        self.mainbutton_calendar.setObjectName("mainbutton_calendar")
        self.mainbuttonsLayout.addWidget(self.mainbutton_calendar, 0, 1, 1, 1)
        self.mainbutton_meal = QtWidgets.QPushButton(self.mainPage)
        self.mainbutton_meal.setMinimumSize(QtCore.QSize(96, 96))
        self.mainbutton_meal.setMaximumSize(QtCore.QSize(96, 96))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.mainbutton_meal.setFont(font)
        self.mainbutton_meal.setObjectName("mainbutton_meal")
        self.mainbuttonsLayout.addWidget(self.mainbutton_meal, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.mainbuttonsLayout, 0, 0, 2, 1)
        self.mainLabel = QtWidgets.QLabel(self.mainPage)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.mainLabel.setFont(font)
        self.mainLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.gridLayout.addWidget(self.mainLabel, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout.addItem(spacerItem, 0, 1, 2, 1)
        self.pageWidget.addWidget(self.mainPage)
        self.mainChildren = QtWidgets.QWidget()
        self.mainChildren.setObjectName("mainChildren")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainChildren)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.childrenTabs = QtWidgets.QTabWidget(self.mainChildren)
        self.childrenTabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.childrenTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.childrenTabs.setElideMode(QtCore.Qt.ElideRight)
        self.childrenTabs.setUsesScrollButtons(False)
        self.childrenTabs.setDocumentMode(False)
        self.childrenTabs.setTabsClosable(False)
        self.childrenTabs.setMovable(False)
        self.childrenTabs.setTabBarAutoHide(False)
        self.childrenTabs.setObjectName("childrenTabs")
        self.childrenTabsFabienne = QtWidgets.QWidget()
        self.childrenTabsFabienne.setObjectName("childrenTabsFabienne")
        self.childrenTabs.addTab(self.childrenTabsFabienne, "")
        self.childrenTabsMio = QtWidgets.QWidget()
        self.childrenTabsMio.setObjectName("childrenTabsMio")
        self.childrenTabs.addTab(self.childrenTabsMio, "")
        self.childrenTabsMika = QtWidgets.QWidget()
        self.childrenTabsMika.setObjectName("childrenTabsMika")
        self.childrenTabs.addTab(self.childrenTabsMika, "")
        self.childrenTabsJona = QtWidgets.QWidget()
        self.childrenTabsJona.setObjectName("childrenTabsJona")
        self.childrenTabs.addTab(self.childrenTabsJona, "")
        self.gridLayout_2.addWidget(self.childrenTabs, 1, 0, 1, 1)
        self.childrenLabel = QtWidgets.QLabel(self.mainChildren)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.childrenLabel.setFont(font)
        self.childrenLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.childrenLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.childrenLabel.setObjectName("childrenLabel")
        self.gridLayout_2.addWidget(self.childrenLabel, 0, 0, 1, 2)
        self.pageWidget.addWidget(self.mainChildren)
        self.mainCalendar = QtWidgets.QWidget()
        self.mainCalendar.setObjectName("mainCalendar")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mainCalendar)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.calendarLabel = QtWidgets.QLabel(self.mainCalendar)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.calendarLabel.setFont(font)
        self.calendarLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calendarLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.calendarLabel.setObjectName("calendarLabel")
        self.gridLayout_3.addWidget(self.calendarLabel, 0, 0, 1, 1)
        self.calendarLayout = QtWidgets.QGridLayout()
        self.calendarLayout.setObjectName("calendarLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.mainCalendar)
        self.calendarWidget.setObjectName("calendarWidget")
        self.calendarLayout.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.calenderTreeview = QtWidgets.QTreeView(self.mainCalendar)
        self.calenderTreeview.setObjectName("calenderTreeview")
        self.calendarLayout.addWidget(self.calenderTreeview, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.calendarLayout, 1, 0, 1, 1)
        self.pageWidget.addWidget(self.mainCalendar)
        self.mainShopping_list = QtWidgets.QWidget()
        self.mainShopping_list.setObjectName("mainShopping_list")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.mainShopping_list)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.shoppinglist_buttonsLayout = QtWidgets.QWidget(self.mainShopping_list)
        self.shoppinglist_buttonsLayout.setMaximumSize(QtCore.QSize(16777215, 300))
        self.shoppinglist_buttonsLayout.setObjectName("shoppinglist_buttonsLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.shoppinglist_buttonsLayout)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.shoppinglist_buttonsPlus = QtWidgets.QPushButton(
            self.shoppinglist_buttonsLayout
        )
        self.shoppinglist_buttonsPlus.setMinimumSize(QtCore.QSize(70, 70))
        self.shoppinglist_buttonsPlus.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.shoppinglist_buttonsPlus.setFont(font)
        self.shoppinglist_buttonsPlus.setObjectName("shoppinglist_buttonsPlus")
        self.gridLayout_8.addWidget(self.shoppinglist_buttonsPlus, 0, 0, 1, 2)
        self.shoppinglist_buttonsMinus = QtWidgets.QPushButton(
            self.shoppinglist_buttonsLayout
        )
        self.shoppinglist_buttonsMinus.setMinimumSize(QtCore.QSize(70, 70))
        self.shoppinglist_buttonsMinus.setMaximumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.shoppinglist_buttonsMinus.setFont(font)
        self.shoppinglist_buttonsMinus.setObjectName("shoppinglist_buttonsMinus")
        self.gridLayout_8.addWidget(self.shoppinglist_buttonsMinus, 2, 0, 1, 2)
        self.shoppinglist_buttonsLCD = QtWidgets.QSpinBox(
            self.shoppinglist_buttonsLayout
        )
        self.shoppinglist_buttonsLCD.setMinimumSize(QtCore.QSize(60, 70))
        self.shoppinglist_buttonsLCD.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.shoppinglist_buttonsLCD.setFont(font)
        self.shoppinglist_buttonsLCD.setAlignment(QtCore.Qt.AlignCenter)
        self.shoppinglist_buttonsLCD.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons
        )
        self.shoppinglist_buttonsLCD.setObjectName("shoppinglist_buttonsLCD")
        self.gridLayout_8.addWidget(self.shoppinglist_buttonsLCD, 1, 0, 1, 1)
        self.shoppinglist_buttonsMoveinlist = QtWidgets.QPushButton(
            self.shoppinglist_buttonsLayout
        )
        self.shoppinglist_buttonsMoveinlist.setMaximumSize(QtCore.QSize(70, 16777215))
        self.shoppinglist_buttonsMoveinlist.setObjectName(
            "shoppinglist_buttonsMoveinlist"
        )
        self.gridLayout_8.addWidget(self.shoppinglist_buttonsMoveinlist, 3, 0, 1, 1)
        self.gridLayout_7.addWidget(self.shoppinglist_buttonsLayout, 1, 1, 1, 1)
        self.shoppinglistChoise = QtWidgets.QTreeWidget(self.mainShopping_list)
        self.shoppinglistChoise.setObjectName("shoppinglistChoise")
        item_0 = QtWidgets.QTreeWidgetItem(self.shoppinglistChoise)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.shoppinglistChoise)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.shoppinglistChoise)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.gridLayout_7.addWidget(self.shoppinglistChoise, 1, 0, 1, 1)
        self.shoppinglistList = QtWidgets.QTableWidget(self.mainShopping_list)
        self.shoppinglistList.setObjectName("shoppinglistList")
        self.shoppinglistList.setColumnCount(2)
        self.shoppinglistList.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.shoppinglistList.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shoppinglistList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shoppinglistList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shoppinglistList.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shoppinglistList.setItem(0, 1, item)
        self.gridLayout_7.addWidget(self.shoppinglistList, 1, 3, 1, 1)
        self.shoppinglistLabel = QtWidgets.QLabel(self.mainShopping_list)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.shoppinglistLabel.setFont(font)
        self.shoppinglistLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shoppinglistLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.shoppinglistLabel.setObjectName("shoppinglistLabel")
        self.gridLayout_7.addWidget(self.shoppinglistLabel, 0, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_7.addItem(spacerItem1, 1, 2, 1, 1)
        self.pageWidget.addWidget(self.mainShopping_list)
        self.mainRecipes = QtWidgets.QWidget()
        self.mainRecipes.setObjectName("mainRecipes")
        self.recipesLabel = QtWidgets.QLabel(self.mainRecipes)
        self.recipesLabel.setGeometry(QtCore.QRect(0, 20, 976, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.recipesLabel.setFont(font)
        self.recipesLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.recipesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.recipesLabel.setObjectName("recipesLabel")
        self.comboBox = QtWidgets.QComboBox(self.mainRecipes)
        self.comboBox.setGeometry(QtCore.QRect(60, 220, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.pageWidget.addWidget(self.mainRecipes)
        self.mainMeal = QtWidgets.QWidget()
        self.mainMeal.setObjectName("mainMeal")
        self.mealLabel = QtWidgets.QLabel(self.mainMeal)
        self.mealLabel.setGeometry(QtCore.QRect(10, 20, 976, 24))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mealLabel.setFont(font)
        self.mealLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mealLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mealLabel.setObjectName("mealLabel")
        self.pageWidget.addWidget(self.mainMeal)
        self.gridLayout_6.addWidget(self.pageWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menubar)
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.menuDatei.addAction(self.actionBeenden)
        self.menubar.addAction(self.menuDatei.menuAction())

        self.retranslateUi(MainWindow)
        self.pageWidget.setCurrentIndex(0)
        self.mainOverview.setCurrentIndex(2)
        self.childrenTabs.setCurrentIndex(0)
        self.wood_inputDial.sliderMoved["int"].connect(self.wood_inputDisplay.display)
        self.shoppinglist_buttonsPlus.clicked.connect(
            self.shoppinglist_buttonsLCD.stepUp
        )
        self.shoppinglist_buttonsMinus.pressed.connect(
            self.shoppinglist_buttonsLCD.stepDown
        )
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.mainbutton_children, self.mainbutton_calendar)
        MainWindow.setTabOrder(self.mainbutton_calendar, self.mainbutton_shopping_list)
        MainWindow.setTabOrder(self.mainbutton_shopping_list, self.mainbutton_recipes)
        MainWindow.setTabOrder(self.mainbutton_recipes, self.mainbutton_meal)
        MainWindow.setTabOrder(self.mainbutton_meal, self.calendarWidget)
        MainWindow.setTabOrder(self.calendarWidget, self.meetings_checkboxKatja)
        MainWindow.setTabOrder(
            self.meetings_checkboxKatja, self.meetings_checkboxFabian
        )
        MainWindow.setTabOrder(self.meetings_checkboxFabian, self.meetings_checkboxMio)
        MainWindow.setTabOrder(self.meetings_checkboxMio, self.meetings_checkboxJona)
        MainWindow.setTabOrder(
            self.meetings_checkboxJona, self.meetings_checkboxFabienne
        )
        MainWindow.setTabOrder(
            self.meetings_checkboxFabienne, self.meetings_checkboxMika
        )
        MainWindow.setTabOrder(self.meetings_checkboxMika, self.meetingsList)
        MainWindow.setTabOrder(self.meetingsList, self.wood_graphicsView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.meetings_checkboxFabienne.setText(_translate("MainWindow", "Fabienne"))
        self.meetings_checkboxKatja.setText(_translate("MainWindow", "Katja"))
        self.meetings_checkboxFabian.setText(_translate("MainWindow", "Fabian"))
        self.meetings_checkboxMio.setText(_translate("MainWindow", "Mio"))
        self.meetings_checkboxJona.setText(_translate("MainWindow", "Jona"))
        self.meetings_checkboxMika.setText(_translate("MainWindow", "Mika"))
        self.mainOverview.setItemText(
            self.mainOverview.indexOf(self.meetingsOverview),
            _translate("MainWindow", "Termine"),
        )
        item = self.childrenOverviewTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Aufgabe"))
        item = self.childrenOverviewTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Handy"))
        item = self.childrenOverviewTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "PS4 / Film"))
        item = self.childrenOverviewTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ausmachen"))
        item = self.childrenOverviewTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fabienne"))
        item = self.childrenOverviewTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mio"))
        item = self.childrenOverviewTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mika"))
        item = self.childrenOverviewTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Jona"))
        self.mainOverview.setItemText(
            self.mainOverview.indexOf(self.childrenOverview),
            _translate("MainWindow", "Kinder"),
        )
        self.wood_inputRadioButtonPiece.setText(_translate("MainWindow", "Päckchen"))
        self.wood_nputRadioButtonStack.setText(_translate("MainWindow", "Palette"))
        self.wood_inputPushButtonAgree.setText(_translate("MainWindow", "PushButton"))
        self.mainOverview.setItemText(
            self.mainOverview.indexOf(self.woodOverview),
            _translate("MainWindow", "Holz"),
        )
        self.mainbutton_recipes.setText(_translate("MainWindow", "Rezepte"))
        self.mainbutton_shopping_list.setText(_translate("MainWindow", "Einkaufen"))
        self.mainbutton_children.setText(_translate("MainWindow", "Kinder"))
        self.mainbutton_calendar.setText(_translate("MainWindow", "Kalender"))
        self.mainbutton_meal.setText(_translate("MainWindow", "Essensplan"))
        self.mainLabel.setText(_translate("MainWindow", "Übersicht"))
        self.childrenTabs.setTabText(
            self.childrenTabs.indexOf(self.childrenTabsFabienne),
            _translate("MainWindow", "Fabienne"),
        )
        self.childrenTabs.setTabText(
            self.childrenTabs.indexOf(self.childrenTabsMio),
            _translate("MainWindow", "Mio"),
        )
        self.childrenTabs.setTabText(
            self.childrenTabs.indexOf(self.childrenTabsMika),
            _translate("MainWindow", "Mika"),
        )
        self.childrenTabs.setTabText(
            self.childrenTabs.indexOf(self.childrenTabsJona),
            _translate("MainWindow", "Jona"),
        )
        self.childrenLabel.setText(_translate("MainWindow", "Kinder"))
        self.calendarLabel.setText(_translate("MainWindow", "Kalender"))
        self.shoppinglist_buttonsPlus.setText(_translate("MainWindow", "+"))
        self.shoppinglist_buttonsMinus.setText(_translate("MainWindow", "-"))
        self.shoppinglist_buttonsMoveinlist.setText(
            _translate("MainWindow", "zur Liste")
        )
        self.shoppinglistChoise.headerItem().setText(
            0, _translate("MainWindow", "Was?")
        )
        __sortingEnabled = self.shoppinglistChoise.isSortingEnabled()
        self.shoppinglistChoise.setSortingEnabled(False)
        self.shoppinglistChoise.topLevelItem(0).setText(
            0, _translate("MainWindow", "Fleisch")
        )
        self.shoppinglistChoise.topLevelItem(0).child(0).setText(
            0, _translate("MainWindow", "Salami")
        )
        self.shoppinglistChoise.topLevelItem(0).child(1).setText(
            0, _translate("MainWindow", "Schnitzel")
        )
        self.shoppinglistChoise.topLevelItem(1).setText(
            0, _translate("MainWindow", "Obst")
        )
        self.shoppinglistChoise.topLevelItem(1).child(0).setText(
            0, _translate("MainWindow", "Apfel")
        )
        self.shoppinglistChoise.topLevelItem(1).child(1).setText(
            0, _translate("MainWindow", "Banane")
        )
        self.shoppinglistChoise.topLevelItem(2).setText(
            0, _translate("MainWindow", "Gemüse")
        )
        self.shoppinglistChoise.topLevelItem(2).child(0).setText(
            0, _translate("MainWindow", "Paprika")
        )
        self.shoppinglistChoise.topLevelItem(2).child(1).setText(
            0, _translate("MainWindow", "Gurke")
        )
        self.shoppinglistChoise.setSortingEnabled(__sortingEnabled)
        item = self.shoppinglistList.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.shoppinglistList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Was?"))
        item = self.shoppinglistList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Wieviel?"))
        __sortingEnabled = self.shoppinglistList.isSortingEnabled()
        self.shoppinglistList.setSortingEnabled(False)
        self.shoppinglistList.setSortingEnabled(__sortingEnabled)
        self.shoppinglistLabel.setText(_translate("MainWindow", "Einkaufen"))
        self.recipesLabel.setText(_translate("MainWindow", "Rezepte"))
        self.mealLabel.setText(_translate("MainWindow", "Essensplan"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
